In [18]:
import pandas as pd
travel_csv = "Resources/Trips_by_Distance.csv"
censusData_csv = "Resources/censusData_df_v1.csv"
travel_df = pd.read_csv(travel_csv)
census_data= pd.read_csv(censusData_csv)
travel_df.head()

travel_df['Date']=pd.to_datetime(travel_df['Date'])
start_date_1 = pd.to_datetime('2019/03/01')
end_date_1 = pd.to_datetime('2019/06/30')
start_date_2 = pd.to_datetime('2020/03/01')
end_date_2 = pd.to_datetime('2020/06/30')
mask1= (travel_df['Date']>=start_date_1) & (travel_df['Date']<=end_date_1)
travel_df1 = travel_df.loc[mask1]
mask2= (travel_df['Date']>=start_date_2) & (travel_df['Date']<=end_date_2)
travel_df2 = travel_df.loc[mask2]
travel_df_new = pd.concat([travel_df1,travel_df2])
travel_df_new

,GEO_ID,State,County,POPESTIMATE2019,Est. Med HH Income (2018 Dollars),Margin of Error,Lat,Lng
0,0500000US01001,Alabama,Autauga County,55869,58786.0,2972.0,32.579182,-86.499655
1,0500000US01003,Alabama,Baldwin County,223234,55962.0,1204.0,30.601074,-87.776333
2,0500000US01005,Alabama,Barbour County,24686,34186.0,2552.0,31.817290,-85.354965
3,0500000US01007,Alabama,Bibb County,22394,45340.0,5618.0,32.956280,-87.142289
4,0500000US01009,Alabama,Blount County,57826,48695.0,2703.0,34.014515,-86.499655
...,...,...,...,...,...,...,...,...
3137,0500000US56037,Wyoming,Sweetwater County,42343,73008.0,3133.0,41.851940,-109.188005
3138,0500000US56039,Wyoming,Teton County,23464,83831.0,5822.0,43.853632,-110.631449
3139,0500000US56041,Wyoming,Uinta County,20226,58235.0,5671.0,41.210740,-110.616892
3140,0500000US56043,Wyoming,Washakie County,7805,53426.0,3654.0,43.834783,-107.703763
3141,0500000US56045,Wyoming,Weston County,6927,52867.0,6921.0,43.927022,-104.472330

In [2]:
travel_df.dtypes

Level                                     object
Date                              datetime64[ns]
State FIPS                               float64
State Postal Code                         object
County FIPS                              float64
County Name                               object
Population Staying at Home               float64
Population Not Staying at Home           float64
Number of Trips                          float64
Number of Trips <1                       float64
Number of Trips 1-3                      float64
Number of Trips 3-5                      float64
Number of Trips 5-10                     float64
Number of Trips 10-25                    float64
Number of Trips 25-50                    float64
Number of Trips 50-100                   float64
Number of Trips 100-250                  float64
Number of Trips 250-500                  float64
Number of Trips >=500                    float64
dtype: object

In [3]:
travel_df_new['Date'].value_counts()

2020-03-13    3194
2019-04-01    3194
2020-05-02    3194
2019-06-11    3194
2020-05-21    3194
              ...
2020-04-22    3194
2019-06-20    3194
2020-04-08    3194
2019-06-06    3194
2020-05-25    3194
Name: Date, Length: 244, dtype: int64

In [4]:
travel_df_new.sort_values(by=['Date'])

,Level,Date,State FIPS,State Postal Code,County FIPS,County Name,Population Staying at Home,Population Not Staying at Home,Number of Trips,Number of Trips <1,Number of Trips 1-3,Number of Trips 3-5,Number of Trips 5-10,Number of Trips 10-25,Number of Trips 25-50,Number of Trips 50-100,Number of Trips 100-250,Number of Trips 250-500,Number of Trips >=500
1605764,County,2019-03-01,47.0,TN,47043.0,Dickson County,7062.0,46221.0,222709.0,48680.0,40082.0,30926.0,33712.0,33551.0,27067.0,5817.0,2028.0,640.0,206.0
1605224,County,2019-03-01,37.0,NC,37039.0,Cherokee County,5168.0,23128.0,79124.0,12688.0,20699.0,9837.0,13887.0,16849.0,2470.0,1709.0,710.0,182.0,93.0
1605225,County,2019-03-01,37.0,NC,37041.0,Chowan County,2547.0,11439.0,50806.0,12111.0,9855.0,5213.0,7062.0,9478.0,4775.0,1856.0,389.0,51.0,16.0
1605226,County,2019-03-01,37.0,NC,37043.0,Clay County,1555.0,9550.0,33088.0,5718.0,7021.0,4674.0,6722.0,6962.0,974.0,511.0,363.0,98.0,45.0
1605227,County,2019-03-01,37.0,NC,37045.0,Cleveland County,15557.0,81790.0,342420.0,67519.0,85861.0,34178.0,53517.0,64414.0,24772.0,8153.0,3220.0,642.0,144.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1503565,County,2020-06-30,21.0,KY,21049.0,Clark County,7804.0,28445.0,117337.0,27449.0,28743.0,16790.0,12689.0,18669.0,8257.0,2102.0,1766.0,684.0,188.0
1503566,County,2020-06-30,21.0,KY,21051.0,Clay County,5083.0,15022.0,48752.0,5843.0,11015.0,7832.0,6090.0,9940.0,5316.0,2022.0,551.0,143.0,0.0
1503567,County,2020-06-30,21.0,KY,21053.0,Clinton County,1169.0,9037.0,40994.0,7114.0,12164.0,8284.0,5811.0,3938.0,1199.0,1532.0,755.0,181.0,16.0
1503569,County,2020-06-30,21.0,KY,21057.0,Cumberland County,653.0,6006.0,29944.0,6168.0,8384.0,3358.0,4832.0,3743.0,1867.0,669.0,186.0,737.0,0.0
1502807,County,2020-06-30,8.0,CO,8029.0,Delta County,7478.0,23475.0,121958.0,34242.0,28048.0,6863.0,16715.0,17847.0,12754.0,4147.0,1130.0,160.0,52.0

In [5]:
travel_df_new.to_csv('pandemictime.csv')

In [6]:
states_df = travel_df_new
states_df.head()
states_sort_df = states_df.sort_values(by=['Date'])
states_sort_df['Date'] = pd.to_datetime(states_sort_df['Date'])
states_sort_df['Date'] = states_sort_df['Date'].dt.strftime('%#m/%#d/%Y')
states_sort_df

,Level,Date,State FIPS,State Postal Code,County FIPS,County Name,Population Staying at Home,Population Not Staying at Home,Number of Trips,Number of Trips <1,Number of Trips 1-3,Number of Trips 3-5,Number of Trips 5-10,Number of Trips 10-25,Number of Trips 25-50,Number of Trips 50-100,Number of Trips 100-250,Number of Trips 250-500,Number of Trips >=500
1605764,County,3/1/2019,47.0,TN,47043.0,Dickson County,7062.0,46221.0,222709.0,48680.0,40082.0,30926.0,33712.0,33551.0,27067.0,5817.0,2028.0,640.0,206.0
1605224,County,3/1/2019,37.0,NC,37039.0,Cherokee County,5168.0,23128.0,79124.0,12688.0,20699.0,9837.0,13887.0,16849.0,2470.0,1709.0,710.0,182.0,93.0
1605225,County,3/1/2019,37.0,NC,37041.0,Chowan County,2547.0,11439.0,50806.0,12111.0,9855.0,5213.0,7062.0,9478.0,4775.0,1856.0,389.0,51.0,16.0
1605226,County,3/1/2019,37.0,NC,37043.0,Clay County,1555.0,9550.0,33088.0,5718.0,7021.0,4674.0,6722.0,6962.0,974.0,511.0,363.0,98.0,45.0
1605227,County,3/1/2019,37.0,NC,37045.0,Cleveland County,15557.0,81790.0,342420.0,67519.0,85861.0,34178.0,53517.0,64414.0,24772.0,8153.0,3220.0,642.0,144.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1503565,County,6/30/2020,21.0,KY,21049.0,Clark County,7804.0,28445.0,117337.0,27449.0,28743.0,16790.0,12689.0,18669.0,8257.0,2102.0,1766.0,684.0,188.0
1503566,County,6/30/2020,21.0,KY,21051.0,Clay County,5083.0,15022.0,48752.0,5843.0,11015.0,7832.0,6090.0,9940.0,5316.0,2022.0,551.0,143.0,0.0
1503567,County,6/30/2020,21.0,KY,21053.0,Clinton County,1169.0,9037.0,40994.0,7114.0,12164.0,8284.0,5811.0,3938.0,1199.0,1532.0,755.0,181.0,16.0
1503569,County,6/30/2020,21.0,KY,21057.0,Cumberland County,653.0,6006.0,29944.0,6168.0,8384.0,3358.0,4832.0,3743.0,1867.0,669.0,186.0,737.0,0.0
1502807,County,6/30/2020,8.0,CO,8029.0,Delta County,7478.0,23475.0,121958.0,34242.0,28048.0,6863.0,16715.0,17847.0,12754.0,4147.0,1130.0,160.0,52.0

In [8]:
covid19 = pd.read_csv("Resources/COVID19.csv")
covid19 = covid19.dropna()
covid19

states_sort_df["Number of cases"]=0
#states_sort_df.head()
for ii in range(len(states_sort_df)):
    fips = states_sort_df["County FIPS"].iloc[ii]
    date = states_sort_df["Date"].iloc[ii]
    try:
        states_sort_df["Number of cases"].iloc[ii] = covid19.loc[covid19["countyFIPS"]==fips,date].iloc[0]
    except:
        continue
        
states_sort_df

C:\Users\rewel\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

,Level,Date,State FIPS,State Postal Code,County FIPS,County Name,Population Staying at Home,Population Not Staying at Home,Number of Trips,Number of Trips <1,Number of Trips 1-3,Number of Trips 3-5,Number of Trips 5-10,Number of Trips 10-25,Number of Trips 25-50,Number of Trips 50-100,Number of Trips 100-250,Number of Trips 250-500,Number of Trips >=500,Number of cases
1605764,County,3/1/2019,47.0,TN,47043.0,Dickson County,7062.0,46221.0,222709.0,48680.0,40082.0,30926.0,33712.0,33551.0,27067.0,5817.0,2028.0,640.0,206.0,0
1605224,County,3/1/2019,37.0,NC,37039.0,Cherokee County,5168.0,23128.0,79124.0,12688.0,20699.0,9837.0,13887.0,16849.0,2470.0,1709.0,710.0,182.0,93.0,0
1605225,County,3/1/2019,37.0,NC,37041.0,Chowan County,2547.0,11439.0,50806.0,12111.0,9855.0,5213.0,7062.0,9478.0,4775.0,1856.0,389.0,51.0,16.0,0
1605226,County,3/1/2019,37.0,NC,37043.0,Clay County,1555.0,9550.0,33088.0,5718.0,7021.0,4674.0,6722.0,6962.0,974.0,511.0,363.0,98.0,45.0,0
1605227,County,3/1/2019,37.0,NC,37045.0,Cleveland County,15557.0,81790.0,342420.0,67519.0,85861.0,34178.0,53517.0,64414.0,24772.0,8153.0,3220.0,642.0,144.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1503565,County,6/30/2020,21.0,KY,21049.0,Clark County,7804.0,28445.0,117337.0,27449.0,28743.0,16790.0,12689.0,18669.0,8257.0,2102.0,1766.0,684.0,188.0,98
1503566,County,6/30/2020,21.0,KY,21051.0,Clay County,5083.0,15022.0,48752.0,5843.0,11015.0,7832.0,6090.0,9940.0,5316.0,2022.0,551.0,143.0,0.0,59
1503567,County,6/30/2020,21.0,KY,21053.0,Clinton County,1169.0,9037.0,40994.0,7114.0,12164.0,8284.0,5811.0,3938.0,1199.0,1532.0,755.0,181.0,16.0,5
1503569,County,6/30/2020,21.0,KY,21057.0,Cumberland County,653.0,6006.0,29944.0,6168.0,8384.0,3358.0,4832.0,3743.0,1867.0,669.0,186.0,737.0,0.0,6
1502807,County,6/30/2020,8.0,CO,8029.0,Delta County,7478.0,23475.0,121958.0,34242.0,28048.0,6863.0,16715.0,17847.0,12754.0,4147.0,1130.0,160.0,52.0,83

In [9]:
states_sort_df.to_csv('Resources/trafficdata_covid19cases.csv')

In [10]:
clean_traffic_cases= states_sort_df[['Level', 'Date', 'State FIPS', 'State Postal Code', 'County FIPS', 'County Name', 'Population Staying at Home', 'Population Not Staying at Home', 'Number of Trips', 'Number of cases']]

In [11]:
clean_traffic_cases

,Level,Date,State FIPS,State Postal Code,County FIPS,County Name,Population Staying at Home,Population Not Staying at Home,Number of Trips,Number of cases
1605764,County,3/1/2019,47.0,TN,47043.0,Dickson County,7062.0,46221.0,222709.0,0
1605224,County,3/1/2019,37.0,NC,37039.0,Cherokee County,5168.0,23128.0,79124.0,0
1605225,County,3/1/2019,37.0,NC,37041.0,Chowan County,2547.0,11439.0,50806.0,0
1605226,County,3/1/2019,37.0,NC,37043.0,Clay County,1555.0,9550.0,33088.0,0
1605227,County,3/1/2019,37.0,NC,37045.0,Cleveland County,15557.0,81790.0,342420.0,0
...,...,...,...,...,...,...,...,...,...,...
1503565,County,6/30/2020,21.0,KY,21049.0,Clark County,7804.0,28445.0,117337.0,98
1503566,County,6/30/2020,21.0,KY,21051.0,Clay County,5083.0,15022.0,48752.0,59
1503567,County,6/30/2020,21.0,KY,21053.0,Clinton County,1169.0,9037.0,40994.0,5
1503569,County,6/30/2020,21.0,KY,21057.0,Cumberland County,653.0,6006.0,29944.0,6
1502807,County,6/30/2020,8.0,CO,8029.0,Delta County,7478.0,23475.0,121958.0,83

In [12]:
clean_traffic_cases.to_csv("clean_traffic_cases.csv")

In [20]:
census_data = census_data.rename(columns={'County': 'County Name'})
census_data

,GEO_ID,State,County Name,POPESTIMATE2019,Est. Med HH Income (2018 Dollars),Margin of Error,Lat,Lng
0,0500000US01001,Alabama,Autauga County,55869,58786.0,2972.0,32.579182,-86.499655
1,0500000US01003,Alabama,Baldwin County,223234,55962.0,1204.0,30.601074,-87.776333
2,0500000US01005,Alabama,Barbour County,24686,34186.0,2552.0,31.817290,-85.354965
3,0500000US01007,Alabama,Bibb County,22394,45340.0,5618.0,32.956280,-87.142289
4,0500000US01009,Alabama,Blount County,57826,48695.0,2703.0,34.014515,-86.499655
...,...,...,...,...,...,...,...,...
3137,0500000US56037,Wyoming,Sweetwater County,42343,73008.0,3133.0,41.851940,-109.188005
3138,0500000US56039,Wyoming,Teton County,23464,83831.0,5822.0,43.853632,-110.631449
3139,0500000US56041,Wyoming,Uinta County,20226,58235.0,5671.0,41.210740,-110.616892
3140,0500000US56043,Wyoming,Washakie County,7805,53426.0,3654.0,43.834783,-107.703763
3141,0500000US56045,Wyoming,Weston County,6927,52867.0,6921.0,43.927022,-104.472330

In [21]:
states_csv = "Resources/fullname_states.csv"
states_df = pd.read_csv(states_csv)
states_df

                   State State Postal Code
0                Alabama                AL
1                 Alaska                AK
2                Arizona                AZ
3               Arkansas                AR
4             California                CA
5               Colorado                CO
6            Connecticut                CT
7               Delaware                DE
8   District of Columbia                DC
9                Florida                FL
10               Georgia                GA
11                Hawaii                HI
12                 Idaho                ID
13              Illinois                IL
14               Indiana                IN
15                  Iowa                IA
16                Kansas                KS
17              Kentucky                KY
18             Louisiana                LA
19                 Maine                ME
20              Maryland                MD
21         Massachusetts                MA
22              Michigan                MI
23             Minnesota                MN
24           Mississippi                MS
25              Missouri                MO
26               Montana                MT
27              Nebraska                NE
28                Nevada                NV
29         New Hampshire                NH
30            New Jersey                NJ
31            New Mexico                NM
32              New York                NY
33        North Carolina                NC
34          North Dakota                ND
35                  Ohio                OH
36              Oklahoma                OK
37                Oregon                OR
38          Pennsylvania                PA
39          Rhode Island                RI
40        South Carolina                SC
41          South Dakota                SD
42             Tennessee                TN
43                 Texas                TX
44                  Utah                UT
45               Vermont                VT
46              Virginia                VA
47            Washington                WA
48         West Virginia                WV
49             Wisconsin                WI
50               Wyoming                WY

In [22]:
left = clean_traffic_cases
right = states_df
traffic_cases_with_states = pd.merge(left, right, on='State Postal Code', how='left')
traffic_cases_with_states

,Level,Date,State FIPS,State Postal Code,County FIPS,County Name,Population Staying at Home,Population Not Staying at Home,Number of Trips,Number of cases,State
0,County,3/1/2019,47.0,TN,47043.0,Dickson County,7062.0,46221.0,222709.0,0,Tennessee
1,County,3/1/2019,37.0,NC,37039.0,Cherokee County,5168.0,23128.0,79124.0,0,North Carolina
2,County,3/1/2019,37.0,NC,37041.0,Chowan County,2547.0,11439.0,50806.0,0,North Carolina
3,County,3/1/2019,37.0,NC,37043.0,Clay County,1555.0,9550.0,33088.0,0,North Carolina
4,County,3/1/2019,37.0,NC,37045.0,Cleveland County,15557.0,81790.0,342420.0,0,North Carolina
...,...,...,...,...,...,...,...,...,...,...,...
779331,County,6/30/2020,21.0,KY,21049.0,Clark County,7804.0,28445.0,117337.0,98,Kentucky
779332,County,6/30/2020,21.0,KY,21051.0,Clay County,5083.0,15022.0,48752.0,59,Kentucky
779333,County,6/30/2020,21.0,KY,21053.0,Clinton County,1169.0,9037.0,40994.0,5,Kentucky
779334,County,6/30/2020,21.0,KY,21057.0,Cumberland County,653.0,6006.0,29944.0,6,Kentucky
779335,County,6/30/2020,8.0,CO,8029.0,Delta County,7478.0,23475.0,121958.0,83,Colorado

In [23]:
left = traffic_cases_with_states
right = census_data
traffic_cases_income = pd.merge(left, right, on=['State', 'County Name'], how='inner')

traffic_cases_income

,Level,Date,State FIPS,State Postal Code,County FIPS,County Name,Population Staying at Home,Population Not Staying at Home,Number of Trips,Number of cases,State,GEO_ID,POPESTIMATE2019,Est. Med HH Income (2018 Dollars),Margin of Error,Lat,Lng
0,County,3/1/2019,47.0,TN,47043.0,Dickson County,7062.0,46221.0,222709.0,0,Tennessee,0500000US47043,53948,50549.0,2297.0,36.145980,-87.301613
1,County,3/2/2019,47.0,TN,47043.0,Dickson County,7719.0,45564.0,215500.0,0,Tennessee,0500000US47043,53948,50549.0,2297.0,36.145980,-87.301613
2,County,3/3/2019,47.0,TN,47043.0,Dickson County,8233.0,45050.0,187453.0,0,Tennessee,0500000US47043,53948,50549.0,2297.0,36.145980,-87.301613
3,County,3/4/2019,47.0,TN,47043.0,Dickson County,7541.0,45742.0,201280.0,0,Tennessee,0500000US47043,53948,50549.0,2297.0,36.145980,-87.301613
4,County,3/5/2019,47.0,TN,47043.0,Dickson County,7452.0,45831.0,210586.0,0,Tennessee,0500000US47043,53948,50549.0,2297.0,36.145980,-87.301613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766643,County,6/26/2020,8.0,CO,8009.0,Baca County,800.0,2785.0,13231.0,13,Colorado,0500000US08009,3581,37500.0,2954.0,37.394731,-102.529803
766644,County,6/27/2020,8.0,CO,8009.0,Baca County,881.0,2704.0,10117.0,13,Colorado,0500000US08009,3581,37500.0,2954.0,37.394731,-102.529803
766645,County,6/28/2020,8.0,CO,8009.0,Baca County,1001.0,2584.0,15758.0,13,Colorado,0500000US08009,3581,37500.0,2954.0,37.394731,-102.529803
766646,County,6/29/2020,8.0,CO,8009.0,Baca County,895.0,2690.0,22217.0,14,Colorado,0500000US08009,3581,37500.0,2954.0,37.394731,-102.529803
766647,County,6/30/2020,8.0,CO,8009.0,Baca County,847.0,2738.0,20585.0,14,Colorado,0500000US08009,3581,37500.0,2954.0,37.394731,-102.529803

In [24]:
traffic_cases_income_clean =  traffic_cases_income[['Level', 'Date', 'State Postal Code', 'State', 'County Name', 'Population Staying at Home', 'Population Not Staying at Home', 'Number of Trips', 'Number of cases', 'Est. Med HH Income (2018 Dollars)', 'Lat', 'Lng' ]]

In [25]:
traffic_cases_income_clean

,Level,Date,State Postal Code,State,County Name,Population Staying at Home,Population Not Staying at Home,Number of Trips,Number of cases,Est. Med HH Income (2018 Dollars),Lat,Lng
0,County,3/1/2019,TN,Tennessee,Dickson County,7062.0,46221.0,222709.0,0,50549.0,36.145980,-87.301613
1,County,3/2/2019,TN,Tennessee,Dickson County,7719.0,45564.0,215500.0,0,50549.0,36.145980,-87.301613
2,County,3/3/2019,TN,Tennessee,Dickson County,8233.0,45050.0,187453.0,0,50549.0,36.145980,-87.301613
3,County,3/4/2019,TN,Tennessee,Dickson County,7541.0,45742.0,201280.0,0,50549.0,36.145980,-87.301613
4,County,3/5/2019,TN,Tennessee,Dickson County,7452.0,45831.0,210586.0,0,50549.0,36.145980,-87.301613
...,...,...,...,...,...,...,...,...,...,...,...,...
766643,County,6/26/2020,CO,Colorado,Baca County,800.0,2785.0,13231.0,13,37500.0,37.394731,-102.529803
766644,County,6/27/2020,CO,Colorado,Baca County,881.0,2704.0,10117.0,13,37500.0,37.394731,-102.529803
766645,County,6/28/2020,CO,Colorado,Baca County,1001.0,2584.0,15758.0,13,37500.0,37.394731,-102.529803
766646,County,6/29/2020,CO,Colorado,Baca County,895.0,2690.0,22217.0,14,37500.0,37.394731,-102.529803
766647,County,6/30/2020,CO,Colorado,Baca County,847.0,2738.0,20585.0,14,37500.0,37.394731,-102.529803

In [26]:
traffic_cases_income_clean.to_csv('traffic_cases_income_clean.csv')

In [27]:
sum_column = traffic_cases_income_clean["Population Staying at Home"] + traffic_cases_income_clean["Population Not Staying at Home"]
Staying_at_home = ((traffic_cases_income_clean["Population Staying at Home"] / sum_column)*100).round(2).astype(str) + '%'
Not_Staying_at_home = ((traffic_cases_income_clean["Population Not Staying at Home"] / sum_column)*100).round(2).astype(str) + '%'
traffic_cases_income_clean["Total Population"] = sum_column
traffic_cases_income_clean["Population Staying at Home Percentage"] = Staying_at_home
traffic_cases_income_clean["Population Not Staying at Home Percentage"] = Not_Staying_at_home
traffic_cases_income_clean["Est. Med HH Income 2018"] = traffic_cases_income_clean["Est. Med HH Income (2018 Dollars)"].map('${:,.2f}'.format)
traffic_cases_income_clean

C:\Users\rewel\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\rewel\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\rewel\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\rewel\anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

,Level,Date,State Postal Code,State,County Name,Population Staying at Home,Population Not Staying at Home,Number of Trips,Number of cases,Est. Med HH Income (2018 Dollars),Lat,Lng,Total Population,Population Staying at Home Percentage,Population Not Staying at Home Percentage,Est. Med HH Income 2018
0,County,3/1/2019,TN,Tennessee,Dickson County,7062.0,46221.0,222709.0,0,50549.0,36.145980,-87.301613,53283.0,13.25%,86.75%,"$50,549.00"
1,County,3/2/2019,TN,Tennessee,Dickson County,7719.0,45564.0,215500.0,0,50549.0,36.145980,-87.301613,53283.0,14.49%,85.51%,"$50,549.00"
2,County,3/3/2019,TN,Tennessee,Dickson County,8233.0,45050.0,187453.0,0,50549.0,36.145980,-87.301613,53283.0,15.45%,84.55%,"$50,549.00"
3,County,3/4/2019,TN,Tennessee,Dickson County,7541.0,45742.0,201280.0,0,50549.0,36.145980,-87.301613,53283.0,14.15%,85.85%,"$50,549.00"
4,County,3/5/2019,TN,Tennessee,Dickson County,7452.0,45831.0,210586.0,0,50549.0,36.145980,-87.301613,53283.0,13.99%,86.01%,"$50,549.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766643,County,6/26/2020,CO,Colorado,Baca County,800.0,2785.0,13231.0,13,37500.0,37.394731,-102.529803,3585.0,22.32%,77.68%,"$37,500.00"
766644,County,6/27/2020,CO,Colorado,Baca County,881.0,2704.0,10117.0,13,37500.0,37.394731,-102.529803,3585.0,24.57%,75.43%,"$37,500.00"
766645,County,6/28/2020,CO,Colorado,Baca County,1001.0,2584.0,15758.0,13,37500.0,37.394731,-102.529803,3585.0,27.92%,72.08%,"$37,500.00"
766646,County,6/29/2020,CO,Colorado,Baca County,895.0,2690.0,22217.0,14,37500.0,37.394731,-102.529803,3585.0,24.97%,75.03%,"$37,500.00"
766647,County,6/30/2020,CO,Colorado,Baca County,847.0,2738.0,20585.0,14,37500.0,37.394731,-102.529803,3585.0,23.63%,76.37%,"$37,500.00"

In [31]:
traffic_cases_income_format =  traffic_cases_income_clean[['Level', 'Date', 'State Postal Code', 'State', 'County Name', 'Population Staying at Home Percentage', 'Population Not Staying at Home Percentage', 'Number of Trips', 'Number of cases', 'Est. Med HH Income 2018', 'Lat', 'Lng' ]]

In [32]:
traffic_cases_income_format

,Level,Date,State Postal Code,State,County Name,Population Staying at Home Percentage,Population Not Staying at Home Percentage,Number of Trips,Number of cases,Est. Med HH Income 2018,Lat,Lng
0,County,3/1/2019,TN,Tennessee,Dickson County,13.25%,86.75%,222709.0,0,"$50,549.00",36.145980,-87.301613
1,County,3/2/2019,TN,Tennessee,Dickson County,14.49%,85.51%,215500.0,0,"$50,549.00",36.145980,-87.301613
2,County,3/3/2019,TN,Tennessee,Dickson County,15.45%,84.55%,187453.0,0,"$50,549.00",36.145980,-87.301613
3,County,3/4/2019,TN,Tennessee,Dickson County,14.15%,85.85%,201280.0,0,"$50,549.00",36.145980,-87.301613
4,County,3/5/2019,TN,Tennessee,Dickson County,13.99%,86.01%,210586.0,0,"$50,549.00",36.145980,-87.301613
...,...,...,...,...,...,...,...,...,...,...,...,...
766643,County,6/26/2020,CO,Colorado,Baca County,22.32%,77.68%,13231.0,13,"$37,500.00",37.394731,-102.529803
766644,County,6/27/2020,CO,Colorado,Baca County,24.57%,75.43%,10117.0,13,"$37,500.00",37.394731,-102.529803
766645,County,6/28/2020,CO,Colorado,Baca County,27.92%,72.08%,15758.0,13,"$37,500.00",37.394731,-102.529803
766646,County,6/29/2020,CO,Colorado,Baca County,24.97%,75.03%,22217.0,14,"$37,500.00",37.394731,-102.529803
766647,County,6/30/2020,CO,Colorado,Baca County,23.63%,76.37%,20585.0,14,"$37,500.00",37.394731,-102.529803

In [33]:
traffic_cases_income_format.to_csv('traffic_cases_income_format.csv')